### ISSUE TITLE
Handle hyperlink on antibody duplicate page

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/scicrunch-antibody-registry#128]
With the duplication detection now looking at non-curated antibodies (done in the scope of #124), the hyperlink shown below might point to a non-curated and therefore non-visible antibody:

![image](https://user-images.githubusercontent.com/19196034/213147242-2e9cb686-5b06-4148-a2c5-d3c04e61eff7.png)

**Comment by filippomc** [comment]
We need to use a direct reference to the accession number

**Comment by filippomc** [comment]
solution: add text mentioning that there's no curated entry yet. @bandrow can you provide the text as agreed?

**Comment by filippomc** [comment]
There is currently no public record with this antibody RRID. This is likely due to this record not yet being curated. Please contact the antibody registry curation team if this antibody is needed for your manuscript. abr-help -at- scicrunch -dot- org
