### ISSUE TITLE
Duplicate antibodies in queue not being detected as duplicates

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#132]
If a user submits a new antibody with cat num "XYZ" they get a new RRID:AB_123.
If the user then immediately submits the same antibody with cat num "XYZ" they will get another new RRID:AB_124.
Instead they should be told it is a duplicate and be given RRID:AB_123.
This happens because the system is only checking CURATED entries for duplicates.
The system needs to check CURATED and QUEUED entries for duplicates.

**Comment by filippomc** [comment]
note: catalog number + vendor

**Comment by filippomc** [comment]
@masonpairish actually the check for the cat number+vendor is working for QUEUED antibodies, but I can see that personal antibodies are not checked. Do we want to check also personal antibodies only on catalog number since the vendor is not relevant? Or maybe the user in that case is equivalent of the vendor?

**Comment by masonpairish** [comment]
I think this ticket was made after the issue was fixed but even personal and non-profit entries should get the same check.

**Comment by filippomc** [comment]
so I get the check for the vendor is relevant for personal and non profit antibodies?

**Comment by masonpairish** [comment]
Yes. Non-profits tend to be consistent in how they name themselves. Personal antibody submitters are not consistent but I check to see if their name exists in our records. If it does I will manually swap vendors and when I do I want to make sure they are using a unique identifier (catalog number).

**Comment by filippomc** [comment]
@masonpairish done.
