### ISSUE TITLE
New vendor created when a new URL and old vendor name is used to register an antibody

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#135]
When registering an antibody, if a new URL is input a new vendor will be created even if an old vendor name is input.
Example: if "https://www.google.com/" is input as the URL and "Abcam" is input as the vendor name, a new vendor named "Abcam" will be created even though "Abcam" is already a vendor.

**Comment by filippomc** [comment]
the vendor name should be unique

**Comment by filippomc** [comment]
@masonpairish done.

**Comment by masonpairish** [comment]
I still get a new vendor.

**Comment by filippomc** [comment]
should catch also the name being the same case insensitive

**Comment by filippomc** [comment]
@masonpairish should also the match on catalog numbers be case insensitive?

**Comment by masonpairish** [comment]
Yes.
