### ISSUE TITLE
Delete vendor page only has a dropdown list - no ability to search

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#137]
This makes it impossible to swap vendors.

**Comment by filippomc** [comment]
The vendors list has the search (see image), so not sure what exactly the need is
![image](https://user-images.githubusercontent.com/46561561/218415430-d432d016-d267-43e5-bacf-d371b25a2e89.png)

**Comment by masonpairish** [comment]
It's the 'swap antibody vendor' page that has no search.
![swap antibody vendor page](https://user-images.githubusercontent.com/50183178/218525210-eb98a6d1-5338-4bb7-bac3-56ba0baafdba.png)

**Comment by filippomc** [comment]
After some digging into, could not find a simple way to replace the dropdown with the search as that's a standard Django handler. Only this could take up to a few days to be implemented. Before spending a lot of time I'm first double checking that the scroller we have is not a viable solution.

![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/d8c8dd1c-ceee-4330-9365-58b82a9cbca7)

Actually typing the first letters does a kind of searching but it's not really workable on all cases as the list is not ordered alphabetically. Would sorting this list work for you @masonpairish?

**Comment by masonpairish** [comment]
Will the list stay sorted as new vendors are added?

**Comment by filippomc** [comment]
yes the idea is to sort the list alphabetically dynamically
