### ISSUE TITLE
No functionality to upload datasheets (pdf) to antibody records.

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#139]
Current workflow is to upload a pdf datasheet (when available) to each curated antibody.
This functionality does not currently exist.

**Comment by filippomc** [comment]
data on antibody_files. Only the curator can add them

**Comment by filippomc** [comment]
need to also implement the import

**Comment by filippomc** [comment]
@afonsobspinto please check this as you have your hands on the import
