### ISSUE TITLE
Change antibody page is missing fields for uniprot and gene id

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#144]

**Comment by filippomc** [comment]
![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/8b0cc9ca-3289-462e-8e9f-8225513ad473) both can be viewed and edited by clicking on the pencil icon near to the symbol name.
This is because antigens are handled and referenced by a separate table now

**Comment by masonpairish** [comment]
This would require the curator to open that dialog for every antibody submitted. The fields should be visible without an extra click.
