### ISSUE TITLE
Antibody details pages shows list of target species (under target antigen) without commas

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#145]
example: mouserathumancatcow
for AB_3064655

**Comment by filippomc** [comment]
this is what I see here ![image.png](https://images.zenhubusercontent.com/5c4f23c24557275e4b89d83b/44b130a4-3f0e-4090-b635-cc6592a80b2d)

**Comment by masonpairish** [comment]
![image](https://user-images.githubusercontent.com/50183178/224370195-ec616a0d-ec41-4fb5-9992-2870fb1aaebf.png)
