### ISSUE TITLE
Search issues

### ISSUE THREAD

**Issue by bandrow** [MetaCell/scicrunch-antibody-registry#171]
is the full data added to https://www.areg.metacell.us/ ??  This looks like there are only a small subset of data included still because all of my searches are failing. Here are the things I see so far, most of which may be addressable by data porting. Several can't.

Search for antibodies is incomplete:

1. general search for TSH fails to produce any useful results on the https://www.areg.metacell.us/  (no direct link possible)
2. search for antigen TSH leads to 1 antibody on the https://www.areg.metacell.us/  (no direct link possible)
The number should be closer to 1000, see:
https://scicrunch.org/resources/data/source/nif-0000-07730-1/search?filter[]=Target%20Antigen:TSH
3. search for biolegend fails to bring up biolegend antibodies on the https://www.areg.metacell.us/ 
should be ~27K results https://scicrunch.org/resources/data/source/nif-0000-07730-1/search?q=*&l=*&filter[]=Vendor:biolegend

4. search within columns covers the result, removing the search box puts users back to the full result set

5. filters do not include most useful columns
6. filters do not work properly (URL does not search all results, I searched for URLs that contain biolegend got back 1, but there are 3 on the page...not sure what is happening there)
7. 0600 this is a catalog number when I search for this it brings back 13000 results but the record that matches exactly does not show up on top. 
8. "Internal Server Error" when I search for 0600, then filter by 0600, then try to see the record by clicking off the filter

**Comment by bandrow** [comment]
Let's consider changing the search features to the rrid.site portal 
this search/database instability is going to reduce the usability of the antibodyregistry

**Comment by bandrow** [comment]
4. search within columns covers the result, removing the search box puts users back to the full result set
Not sure what's the desired behaviour here. Should we reser column filters for new searches?
-yes please reset the filters when a new search is done. The filters do not work as search so it is not predictable what they will do. 

5. filters do not include most useful columns
Some columns are not visible by default, and can be added through the "table settings" button. If anything else is missing, we can add it
vendor name
same issue 12. Please add search on top of all columns, especially the "proper citation" and the "Link to Vendor" columns, I currently can't search for vendor because neither one of the vendor containing columns has a search on it.
Filters are disabled for derived columns as it's not clear what exactly the filter should work on (the vendor name or the url?).
The simplest solution would be to add the raw url and vendor fields which might be optionally enable and filter on.
- Here I mean that the vendor name is not searchable. This must change before release. Any way you want to implement that is fine, but the search for catalog number is difficult to accomplish without a vendor search. The simplest choice may be to create the clean vendor field and search on top of that. It can be a hidden field, but if it is in the dropdown then it should be workable

7. 0600 this is a catalog number when I search for this it brings back 13000 results but the record that matches exactly does not show up on top.
0600 is a actually a good case as 21 results are shown the exact match does show up on top. Maybe something else was wrong there.
-Yes there seems to be multiple states that are happening here. The first state is usually functioning as expected, but if you wait for about 30 seconds then in about 50% of the cases the search resets itself and the results are then quite bad. I can't predict why this happens, but I have seen it on multiple searches. 

9. Please update the big filter button to a really really noticeable color so that when it is on it is visible.
Sorry not sure I get this
-Ok, I am not sure how to specify. We need to make sure that users know that they are filtering. So highlighting the filtered column in some way is one possible way to do this. The users will be confused if that does not happen. Some of this will be removed if the filters reset when searching again (See #4 and duplicated by #10).

13. Please add a link to the RRID portal https://scicrunch.org/resources/data/source/nif-0000-07730-1/search in case people are confused by the new search paradigm.
Adding the link together with the "No results found" message is what you expect?
-No, please add a Beta tag to the search function; and please add a link just underneath it to the search page since many searches will simply come back with no usable results and not no results. 

 
I understand that we stopped working on search, it made sense before I had the full dataset, because I could always just attribute the search issues with there not being the full data or there not being a stable system. We are not that far off, but we need to be more explicit with what we currently have implemented as it will absolutely make people complain and at least implement the search for vendor and clean up a few bugs.

**Comment by bandrow** [comment]
I just had our group ~20 people test the antibody registry and here is the result; ~30% of searches ended in 500 errors, only one person was able to log in to test further; lots of good info from various people some of which can be easily fixable (FAQs do not respond to page search functionality because they are all closed by default) or that search function starts hitting the database after 1 character which overwhelms the system quickly with a few concurrent users - ajax errors, and the fact that the Chinese message is duplicated in chinese but not english, to things that will be harder to fix. For our conversation on Friday, you may want to take a look at this user testing data to see what is easy to fix and we can prioritize on Friday. 

https://docs.google.com/presentation/d/1q65vzAfH7x23CKZB-OD2Wh6V-B6II1BM725rZlhhdKQ/edit?usp=sharing

**Comment by filippomc** [comment]
Thanks, starting working on the issues we must obviously fix:
1. 500 errors
2. Search on vendor name and other related data
3. Filter by vendor name
4. Inconsistent search (most certainly due to the form submission while typing)
