### ISSUE TITLE
Delete vendor/swap vendor issue

### ISSUE THREAD

**Issue by masonpairish** [MetaCell/scicrunch-antibody-registry#189]
In the vendor table there were two instances of "STEMCELL Technologies".
One instance had only 1 antibody record. The other instance had hundreds of records.
I swapped the vendor with 1 antibody record to the one with hundreds of records.
I looked at the remaining vendor and it said there was only one antibody record!!!!
Then I did a search on the main page for "STEMCELL Technologies" and it returned 517 records.
But the vendor name was "ERROR".
![image](https://github.com/MetaCell/scicrunch-antibody-registry/assets/50183178/9b0cc64e-2716-47f6-b8f7-dc8b85fa7011)

**Comment by masonpairish** [comment]
I was using the following site: https://www.areg.metacell.us/

**Comment by filippomc** [comment]
the same with two vendors with a similar but not exact vendor name did work
