### ISSUE TITLE
Home > Table Settings > Hide all > Show all click sequence results in a react error

### ISSUE THREAD

**Issue by gidili** [MetaCell/scicrunch-antibody-registry#210]
On dev: 

<img width="1540" alt="Screenshot 2024-02-16 at 18 16 46" src="https://github.com/MetaCell/scicrunch-antibody-registry/assets/68134/e49012da-210c-44bb-b407-1c39c055ab06">

**Comment by filippomc** [comment]
Already tracked on Jira
