### ISSUE TITLE
Submit an antibody frontend

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#23]
See figma https://www.figma.com/proto/JZGpS1A8BJoVyAFLeVQZM1/Antibody-Registry?node-id=991%3A33850&scaling=scale-down&page-id=102%3A38490

Depending on the antibody type, the available fields are different (for instance, all the vendors stuff is only relevant for the commercial antibody submission).

Refer to this document https://docs.google.com/spreadsheets/d/1K_wCdqpIKSu7dxuCAq3QRzLcaXIcCUwwTgeAWKWgTmo/edit#gid=0 for the correct set of fields, labels, help text, etc

- [x] Implement route /submit with the main orchestration component
- [x] Implement selector page (1/3)
- [x] Implement commercial antibody page form component and logic
- [x] Implement personal antibody page form component and logic
- [x] Implement custom/other antibody page form component and logic
- [x] Implement "Antibody successfully submitted" component page
- [x] Implement multi page logic
- [x] Attach submission to the backend

**Comment by bandrow** [comment]
Rules for submitting antibodies:

At time of submission: If there exists a CURATED entry (antibody/kit) with the same VENDOR_ID and CAT_NUM the new entry gets the AB_ID of the previous entry and a new ACCESSION (aka AB_ID_OLD) and a new IX. The submitter receives a message indicating they have made a duplicate submission.

"The Antibody you Entered is a Duplicate, which will be Rejected
We have found that the antibody you entered already exists in our system.
The ID associated with the antibody is RRID:AB_2298772.
Search antibody by [catalog number](http://antibodyregistry.org/search?q=MAB377) and save time.

您所提交的抗体已经存在于我们的系统中，此次申请将会被拒绝
我们发现您所提交的抗体已经存在于我们的系统中，它的ID 是 RRID:AB_2298772.
如果查询抗体的[目录编号](http://antibodyregistry.org/search?q=MAB377)，您将会更快捷地找到您所需要的抗体。


If you have any questions feel free to contact us at [abr-help@scicrunch.org](mailto:abr-help@scicrunch.org)."

If there is not a match the entry gets a new AB_ID and the ACCESSION (aka AB_ID_OLD) is the same as the AB_ID. The entry gets a new IX.

Message to the user: 
"Successfully Added your Antibody
Your antibody has been successfully submitted to the Antibody Registry.
You should receive an email response from [curation@scicrunch.com ](mailto:curation@scicrunch.com)in 1 business day with your antibody's official RRID.
If approved, the data will be publicly available at [antibodyregistry.org](http://antibodyregistry.org/) in approximately 8 business days.
If you have any questions feel free to contact us at [abr-help@scicrunch.org](mailto:abr-help@scicrunch.org).

Your temporary ID is RRID:AB_2923405."
