### ISSUE TITLE
Migrate users

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#38]
Import users from users_antibody.csv.

Users need to be imported on keycloak

Need also to see if we can import passwords too -- only way being maintaining the same hashing method.

As users are migrated, also the association antibody-user should be -- See also #75

**Comment by filippomc** [comment]
orcid users: the attribute orcid needs to be set on keycloak for the user to be recognized

**Comment by filippomc** [comment]
banned users: no need to import

**Comment by afonsobspinto** [comment]
Potentially useful links:
https://stackoverflow.com/a/40355313/16197038
https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/login-settings/forgot-password.html
https://technology.first8.nl/programmatically-adding-users-in-keycloak/
