### ISSUE TITLE
How to handle null antibody vendor URL

### ISSUE THREAD

**Issue by afonsobspinto** [MetaCell/scicrunch-antibody-registry#66]
The provided 'supplemental data file.xlsx' seems to state that the url field is required:
<details>

![image](https://user-images.githubusercontent.com/19196034/191323459-71464491-173e-4b9b-8fff-c233d7ea2d3c.png)

</details>

However in the data we got, there are a couple of entries with no URL. What should we do with those?~

<details>

![image](https://user-images.githubusercontent.com/19196034/191324058-f72bce51-a1ba-4642-9c79-4f8f9eb9ae3c.png)

</details>

**Comment by filippomc** [comment]
if it's personal it can be blank as in the past was not required.
In this case it's linked to a vendor which does not have a url
