### ISSUE TITLE
Backoffice personalizations

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#71]
The goal is to have all the functionalities of the current backoffice as possibly more that help save curation time

**Comment by masonpairish** [comment]
keep on backlog

**Comment by masonpairish** [comment]
Main curator page (only filter is a search for catalog number/vendor/RRID and nothing is editable):
![01 ant reg curator list of recent submissions](https://user-images.githubusercontent.com/50183178/198093293-b8832502-dd08-4a18-b07e-459d6c8c22a3.png)
Edit entry page part 1 (first 4 fields are uneditable. The rest are free text except for clonality):
![02 ant reg curator edit entry part 1](https://user-images.githubusercontent.com/50183178/198093450-07a68c25-cb64-42e5-aed7-3518420ab52d.png)
Edit entry page part 2 (free text except for vendor type):
![03 ant reg curator edit entry part 2](https://user-images.githubusercontent.com/50183178/198093509-91f6b4bc-089d-4d77-80d0-0150f7a0373e.png)
List of recently added vendors (nothing is editable):
![04 ant reg curator list of recentrly added vendors](https://user-images.githubusercontent.com/50183178/198093602-36f3edee-dfb6-4680-acfc-4a02740c29cd.png)
Edit vendor page (name and synonyms are free text):
![05 ant reg curator edit vendor](https://user-images.githubusercontent.com/50183178/198093703-c2453405-d8ff-4cc6-aa3f-73ecc3d47532.png)
Delete/Swap vendor popup (vendor id is a number):
![06 ant reg curator delete vendor popup](https://user-images.githubusercontent.com/50183178/198093804-ce2101b7-5fda-4c00-9338-73ee7d8c2f49.png)
List of recent vendor domains (can accept or reject):
![07 ant reg curator list of recent vendor domains](https://user-images.githubusercontent.com/50183178/198093885-8a030b54-72ba-431b-a02e-25dbf1057212.png)
Add vendor domain popup (domain is a URL, vendor id is a number):
![07 ant reg curator list of recent vendor domains](https://user-images.githubusercontent.com/50183178/198093987-0096808e-f63e-49e8-b9e1-dfc5907235ac.png)

> automations on save
Not sure what this means.
> specific curation workflows -- things like a user can do something after another user did something else
Users can only edit their own submissions.
> custom views
None?
> style changes
None?

**Comment by filippomc** [comment]
AB_ should be seen in the antibodies list
It's fine to keep all fields writable

**Comment by aranega** [comment]
Hi @masonpairish, hi @filippomc 

I'm still working on the backend customisation. I still didn't finish everything, but I covered points listed in the discussion.

Here are the admin menus for the antibody list and edition:
 
![edit_antibodies1](https://user-images.githubusercontent.com/2317394/206812119-d6bc342e-4379-4b0c-b305-46dbf44f8208.png)
![list_antibodies](https://user-images.githubusercontent.com/2317394/206812122-40fae142-7907-43cf-95ce-def037f4101f.png)
![edit_antibodies2](https://user-images.githubusercontent.com/2317394/206812121-aa7aa7a6-0825-4b3c-9988-c5ef0337fbd8.png)

Here are the admin menus for the vendor list, edition and deletion if no antibody is linked to the vendor:
![list_vendors](https://user-images.githubusercontent.com/2317394/206812299-94f51823-fe49-41ae-bd3c-f5e956ee26c6.png)
![edit_vendors](https://user-images.githubusercontent.com/2317394/206812298-20fa2a77-b688-4c20-899b-d8bbd4e56a62.png)
![delete_vendors_noantibody](https://user-images.githubusercontent.com/2317394/206812294-e0e902da-b122-4898-97d0-0c042554606f.png)


Here are the admin menus for the vendor edition and deletion if there is antibodies linked to the vendor:
![edit_vendors2](https://user-images.githubusercontent.com/2317394/206812383-ee1f79b7-7dd4-482c-a315-9b33bc2613f7.png)
![delete_vendors_antibody](https://user-images.githubusercontent.com/2317394/206812380-deca8cad-f3cb-4a7a-85ee-844f060e8575.png)


And here is the list of vendor domains. There is a quick action to set which domains are visible or not:
![list_domains](https://user-images.githubusercontent.com/2317394/206812532-d8a7e6c0-9cf0-423a-82bc-4356b791301e.png)

Regarding this last screen, the `is visible` quick action in the list of vendor domain is what I interpreted from the `accept/reject` from in the screenshot. Did I understand well what was the meaning of `accept/reject` here? (I really suppose I didn't).

**Comment by masonpairish** [comment]
RE: vendor list
The filter by status is not needed. Vendors themselves do not have a curation status.
There should be a filter to show vendors that have non-curated domains.
If the filter for non-curated domains is implemented then the 'vendor domains' and 'vendor synonyms' pages are not needed and can be removed from the menu.

**Comment by aranega** [comment]
@masonpairish Thanks for the feedback!

The `status` filter for the Vendors is actually a filter regarding the 'vendor domains' status. It appears `Status` as it is related to the status of the vendor domain. 

I can see how to change the title and/or constraint to only non-curated domains in the filter if you prefer?
