### ISSUE TITLE
Multiple upload submission

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#74]

**Comment by masonpairish** [comment]
keep on backlog

**Comment by filippomc** [comment]
@masonpairish @bandrow can you please share with us some example of multiple upload file and a description of the exact workflows?

**Comment by masonpairish** [comment]
Can you view this page:
https://github.com/SciCrunch/AntibodyRegistry-UI/wiki/Bulk-Uploading-via-CSV
[antibody registry upload an update.csv](https://github.com/MetaCell/scicrunch-antibody-registry/files/10025564/antibody.registry.upload.an.update.csv)
[antibody registry upload new records.csv](https://github.com/MetaCell/scicrunch-antibody-registry/files/10025565/antibody.registry.upload.new.records.csv)

**Comment by filippomc** [comment]
# Bulk Uploading Antibodies via CSV

**Context:** Within the 'Curate Antibodies' tab in [antibodyregistry.org](http://antibodyregistry.org), there exists an upload button that allows one to load in a CSV file to either add new antibodies or update existing ones.

* **Note:** One has to be logged in and assigned as a curator. This can be done by setting one's level to `1` in the `user_antibody` table within MySQL (nif_eelg); refer to whomever has access to the databases.

## Breakdown of the Upload Feature
* Given a CSV file, it can contain new antibodies to be added or existing ones to be updated.
    * **CSV Headers:** ab_name, vendor, catalog_num, url, ab_target, target_species, clonality, source_organism, clone_id, product_isotype, product_conjugate, product_form, comments, defining_citation, target_subregion, target_modification, ab_target_entrez_gid, disc_date, commercial_type, uniprot_id, epitope, cat_alt, [ab_id], [ab_id_old], [ix].

* Each record in the CSV file 'can' have an ab_id and either an ab_id_old or an ix, where having them entails an existing antibody, while having none implies that it's a new antibody (not necessarily always the case). For updating records, the preferred CSV format is to include the ab_id and the ix because looking up records by ix is fastest.

### Upload Options:
**The following shows the different values for each of the fields**
* **"For New:"** can be either `Don't Insert New Antibodies` or `Insert New Antibodies`.
* **"For Extant:"** can be `Do Nothing with Duplicates` or `Update` or `Make duplicate`.
* **"Method:"** can be either `Update filled columns in CSV` or `Overwrite`. 
    * **Note:** This feature only applies if `Update` was selected for the 'For Extant' field.

**Based on what was selected, the uploading process will handle each record accordingly**
* **"For New":**
    * If **Don't Insert New Antibodies** was selected, then in the case where a new antibody record is found it will be ignore.

    * If **Insert New Antibodies** was selected, then in the case where a new antibody record is found it will be added.

* **"For Extant":**
    * If **Do Nothing with Duplicates** was selected, then in the case where the antibody record is a duplicate, nothing is done.

    * If **Update** was selected, then in the case where the antibody record is a duplicate, the record with the same ix (if provided) or the oldest record with the same ab_id & ab_id_old (if both were provided) or vendor_id & catalog_num (if ab_id & ab_id_old or ix were not given) will be updated.  

    * If **Make a Duplicate** was selected, then in the case where the antibody record is a duplicate, it will retain the ab_id of the original record and create a new ab_id_old for the duplicate.

* **"Method":**
    * If **Update filled columns in CSV** was selected, then one can provide the bare minimum within a CSV file when doing a bulk upload to update existing records. (provide only fields that need to be changed).
        * **Required:** Either (ab_id & ab_id_old or ix) or (vendor_id & catalog_num) needs to be given.
        * **Note:** To remove an existing value in a field, use 'remove' (without the quotes) in the csv to flag that this field needs to be empty.

    * If **Overwrite** was selected, then all fields will be updated corresponding to what was provided in the CSV file. 
        * **Warning:** If a field is empty in the CSV, then the corresponding field in the database table will be overwritten, overwriting an existing value.
        * **Note:** This feature was kept to have access to the old functionally, which required more work for the curator.

**Comment by afonsobspinto** [comment]
@masonpairish @bandrow 1 csv can contain both entries to add and update or is it either one or another?

**Comment by masonpairish** [comment]
Typically, if I do not provide the ab_id & ab_id_old or ix then there could be both new and old entries. The default behavior is simply to check if the entries exist or not. Then I can re-upload the same file depending on if I want to add new or update old.
