### ISSUE TITLE
Final testing and bug fixes

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#79]
Necessary before a proper launch on live

**Comment by masonpairish** [comment]
keep on backlog

**Comment by masonpairish** [comment]
site displays rejected records and in queue records - those must be hidden
	proper citation column should display: vendor cat# xxxx, rrid:AB_83745807348587837 currently looks like: (Alpco Diagnostics#22-BP3HU-E01, RRID:AB_2923277)
	no FAQ page found

**Comment by masonpairish** [comment]
add workflow
	vendor is not set from url. 
	Link to edit entry does not work. 
	Adding an old antibody doesn't get proper rrid assigned.

**Comment by filippomc** [comment]
> Link to edit entry does not work

@masonpairish the editing all happens in the backoffice, it is the case that the user can edit the previously submitted antibody?

**Comment by masonpairish** [comment]
@bandrow @filippomc 
This feature works perfectly in the old antibody registry. Most users simply did not know it exists and they tend to submit an antibody twice if they make a mistake. They rarely email (that I am aware of).
This feature should work in the new version. This is the reason the persistent link to 'My Submissions' was added on the front page.

**Comment by filippomc** [comment]
@masonpairish understood, creating a separate card for it
