### ISSUE TITLE
Go live

### ISSUE THREAD

**Issue by filippomc** [MetaCell/scicrunch-antibody-registry#81]
- [x] Create live deployment
- [x] Dimensioning based on current user base
- [x] set session timeout to 3 hours
- [x] set up monitoring
- [x] Setup ORCID connection
- [x] google analytics
- [ ] configure antibodyregistry.org smtp 
- [x] update with latest data
- [x] upload files
- [x] update deployment with domain antibodyregistry.org
- [x] Update references do domain on keycloak as needed
- [x] switch dns -- avoid downtimes

**Comment by masonpairish** [comment]
keep on backlog

**Comment by filippomc** [comment]
Dimension for peaks of about 3000 users per day

**Comment by filippomc** [comment]
it's important during the transition period to keep the data up to date

**Comment by filippomc** [comment]
GA code: 386643482

**Comment by filippomc** [comment]
@bandrow @masonpairish, still using the Metacell SMTP to send emails.
